#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: myclaim
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
##  hostPath:
##    path: /data/pv0001/
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
#        volumeMounts:
#            - name: mongo-persistent-storage
#              mountPath: /data/db
#      volumes:
#        - name: mongo-persistent-storage
#          persistentVolumeClaim:
#            claimName: pv0001Claim
#          hostPath:
#            path: /data/pv0001/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: springboot-docker
spec: 
  replicas: 3
  template: 
    metadata: 
      labels: 
        run: springboot-docker
    spec: 
      containers: 
        - image: elizabetht/kubernetes-mongo-docker-demo:latest
          name: springboot-docker
          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-docker
  labels:
      run: springboot-docker
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    run: springboot-docker
  type: LoadBalancer
---
