apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: springboot-docker
spec: 
  replicas: 3
  template: 
    metadata: 
      labels: 
        run: springboot-docker
    spec: 
      containers: 
        - 
          image: elizabetht/kubernetes-mongo-docker-demo:latest
          name: springboot-docker
          ports: 
            - 
              containerPort: 8080