apiVersion: v1
kind: Service
metadata:
  name: springboot-docker
  labels:
      run: springboot-docker
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    run: springboot-docker
  type: LoadBalancer